### ISSUE TITLE
gp大佬，我遇到了运行时的问题，启动app层的方法，提示空指针，对应报错代码是deviceItemService.list(queryWrapper);，是一个service注入

### ISSUE THREAD

**Issue by LiaoXH** [lgp547/any-door#22]
17:58:34.210 [Attach Listener] INFO  i.g.l.a.u.SpringUtil - [doInit,64] - mmmmmmmmmmmmmmmmmmm any-door 1.3.2 springUtil init end mmmmmmmmmmmmmmmmmmm
17:58:34.249 [ForkJoinPool.commonPool-worker-19] INFO  i.g.l.a.c.AnyDoorService - [lambda$futureResultLogConsumer$3,118] - any-door run listDevice exception: 
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.doInvoke(AnyDoorHandlerMethod.java:97)
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.invokeSync(AnyDoorHandlerMethod.java:40)
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.lambda$invokeAsync$0(AnyDoorHandlerMethod.java:33)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	... 8 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.doInvoke(AnyDoorHandlerMethod.java:95)
	... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.ruoyi.web.controller.application.DeviceApplicationService.listDevice(DeviceApplicationService.java:169)
	... 16 common frames omitted

**Comment by lgp547** [comment]
说明获取到的Bean对象有点不对，通过该类名会获取多个对象的吗？ com.ruoyi.web.controller.application.DeviceApplicationService

**Comment by LiaoXH** [comment]
是的，其他方法，包括task任务等，都是Autowired注入的service调用空指针异常，像是注入失败一样

**Comment by lgp547** [comment]
目前任意门对这种通过一个类获取到的多个对象没有很好的交互方式，下一个版本会随机获取一个对象，今天发布1.3.3版本，预计明天会有推送

**Comment by LiaoXH** [comment]
好的，感谢大佬

**Comment by LiaoXH** [comment]
我目前更新了插件，实例化的类还是一个空对象
![image](https://github.com/lgp547/any-door/assets/88544549/1c9b73f2-c083-41f4-be53-9c186702d380)
![image](https://github.com/lgp547/any-door/assets/88544549/ba2548c0-8898-496f-9a26-3905a5877644)

**Comment by lgp547** [comment]
尝试一下正常的用controller进行调用当前类看看

**Comment by LiaoXH** [comment]
![image](https://github.com/lgp547/any-door/assets/88544549/165fe5a0-dbba-47f6-a0c5-a2d9f24e532f)
获取到的app层也是null

**Comment by lgp547** [comment]
尝试一下使用插件的mvc模式看看
![image](https://github.com/lgp547/any-door/assets/51388510/48d02329-9513-42b6-88be-5981ce03ef63)

配置成功后，再重新启动项目

**Comment by LiaoXH** [comment]
我试试

**Comment by LiaoXH** [comment]
![image](https://github.com/lgp547/any-door/assets/88544549/43ba1ebb-3a45-474e-8207-4eac5ed8cbe1)
idea报告了一个这样的问题，我发现我发送的http请求也失效了，同意是空指针
![image](https://github.com/lgp547/any-door/assets/88544549/d81b58af-28f0-4daa-ad75-e665d293e35a)

**Comment by lgp547** [comment]
你用http进行请求也存在这个问题，说明是你项目代码有问题。。。

**Comment by LiaoXH** [comment]
应该是我项目问题吧，可能不兼容。本地以及测试环境调用都是正常的

**Comment by lgp547** [comment]
我是指你直接通过调用get方法的http是否正常，正常的话就是插件没兼容，可以提交个demo？或者你尝试debug一下？

**Comment by lgp547** [comment]
看看这个方法返回的对象和正常调用的mvc对象是否有区别：io.github.lgp547.anydoor.attach.AnyDoorAttach#getInstance
引入两个依赖：
        <dependency>
            <groupId>io.github.lgp547</groupId>
            <artifactId>any-door-attach</artifactId>
            <version>1.4.0</version>
        </dependency>
<dependency>
    <groupId>io.github.lgp547</groupId>
    <artifactId>any-door-core</artifactId>
    <version>1.4.0</version>
</dependency>

**Comment by lgp547** [comment]
进57行方法里面看看，是怎么拿的

**Comment by lgp547** [comment]
插件要兼容这种情况，而不是项目问题，给着别人的插件，早喷它了不是

**Comment by lgp547** [comment]
可能是spring的版本问题，你的版本是多少

**Comment by LiaoXH** [comment]
SpringVersion.getVersion() = 5.3.20
SpringBootVersion.getVersion() = 2.5.14

**Comment by lgp547** [comment]
不用插件，直接调用get方法，是否会有找不到依赖注入的服务问题？

**Comment by LiaoXH** [comment]
不会

**Comment by lgp547** [comment]
麻烦确定下是否懒加载引起的
- 加个注解试试
- 项目启动关闭全局懒加载

**Comment by LiaoXH** [comment]
不是懒加载引起的，我的spring配置用的是ConfigurableListableBeanFactory 去getBean的

**Comment by lgp547** [comment]
升级到2.0.0版本再试试

**Comment by LiaoXH** [comment]
收到，感谢支持
