### ISSUE TITLE
idea升级到2024.1后插件报错

### ISSUE THREAD

**Issue by Henvy-Mango** [lgp547/any-door#38]
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: ZGC Cycles, ZGC Pauses
Memory: 4096M
Cores: 16
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  io.github.lgp547.any-door-plugin (2.1.3)
Kotlin: 241.14494.240-IJ

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.github.lgp547.anydoorplugin.action.AnyDoorOpenAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.github.lgp547.any-door-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by lgp547** [comment]
升级到最新的版本2.1.4

**Comment by Henvy-Mango** [comment]
问题貌似还在

![image](https://github.com/lgp547/any-door/assets/33375791/e5baa666-7f21-4127-b5ce-f889f5591bcd)
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.github.lgp547.anydoorplugin.action.AnyDoorAgainOpenAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.github.lgp547.any-door-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by Henvy-Mango** [comment]
> 升级到最新的版本2.1.4

https://github.com/lgp547/any-door/issues/38#issuecomment-2049270978

**Comment by lgp547** [comment]
漏了类 尴尬了

**Comment by lgp547** [comment]
卸载重新下载即可，小修复就没更新版本了 最新版本：2.1.4
