### ISSUE TITLE
执行feign调用时报错

### ISSUE THREAD

**Issue by nicangtianws01** [lgp547/any-door#47]
## 现象
调用feign接口时报错

## 环境
idea version: 2024.2.2
plugin version: 2.2.0
springboot version: 2.3.12.RELEASE
springcloud version: 2.2.9.RELEASE

## 报错日志
```
any-door run order exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.condition.OnPropertyCondition]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334)
	at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.doRegisterBean(AnnotatedBeanDefinitionReader.java:254)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:147)
	at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:137)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.register(AnnotationConfigApplicationContext.java:162)
	at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:124)
	at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:102)
	at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:146)
	at org.springframework.cloud.loadbalancer.support.LoadBalancerClientFactory.getInstance(LoadBalancerClientFactory.java:60)
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.choose(BlockingLoadBalancerClient.java:81)
	at org.springframework.cloud.client.loadbalancer.InterceptorRetryPolicy.canRetry(InterceptorRetryPolicy.java:59)
	at org.springframework.retry.support.RetryTemplate.canRetry(RetryTemplate.java:375)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:278)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	at org.springframework.cloud.openfeign.loadbalancer.RetryableFeignBlockingLoadBalancerClient.execute(RetryableFeignBlockingLoadBalancerClient.java:83)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy207.getCloseToday(Unknown Source)
	at 业务代码包路径.ServiceImpl.xxx(ServiceImpl.java:738)
	at 业务代码包路径.ServiceImpl.order(ServiceImpl.java:147)
	at 业务代码包路径.ServiceImpl$$FastClassBySpringCGLIB$$2544632a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at 业务代码包路径.ServiceImpl$$EnhancerBySpringCGLIB$$50813429.order(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.doInvoke(AnyDoorHandlerMethod.java:113)
	at io.github.lgp547.anydoor.core.AnyDoorHandlerMethod.lambda$invokeAsync$0(AnyDoorHandlerMethod.java:31)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.autoconfigure.condition.OnPropertyCondition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at io.github.lgp547.anydoor.common.util.AnyDoorClassloader.loadClass(AnyDoorClassloader.java:52)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324)
	... 40 more
```

**Comment by nicangtianws01** [comment]
换成mvc模式就行了
